name: "Publish Root PSSailPoint Module"

on:
  workflow_dispatch:
  
jobs:
  publish_powershell_sdk:
    name: Publish powershell SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}


      - name: Publish Module
        shell: pwsh
        run: |
          $DebugPreference="Continue"
          Install-Module -Name Tm.Beta -Force
          Install-Module -Name Tm.V3 -Force
          Install-Module -Name Tm.V2024 -Force
          Publish-Module `
              -Path './Tm' `
              -NuGetApiKey ${{ secrets.PS_GALLERY_TOKEN }} `
              -Verbose -Force
          
